name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t m1-app .

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: m1-app
          format: table
          exit-code: '0'
          severity: CRITICAL